### ISSUE TITLE
Deutsche Bank - Content Removal Request

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [ohthehugemanatee/db-to-ynab-golang#1]
Greetings,

My name is Lawrence Peterson from iZoologic and I am reaching out on behalf of Deutsche Bank.

I am an authorized representative of Deutsche Bank and it has come to their attention that a file associated with Deutsche Bank has been uploaded to Github without prior authorization.

As an uploader of the content, we ask that you delete or remove anything related to our client on this repository as soon as possible as requested by our client.

Here is the link to the file uploaded on Github: https://github.com/ohthehugemanatee/db-to-ynab-golang/commit/c74ac75bb49082c8811ebdf8736ef14baa8747d2

We would appreciate your cooperation in removing all our client related content to the said repository.

This is our contact details:

Address: Level 30, The Leadenhall Building,
122 Leadenhall Street, EC3V 4AB
City of London, UNITED KINGDOM
Email: izoolabs@izoologic.com
Phone + 44 20 3734 2726  

I am providing this notice in good faith and with the reasonable belief that rights my company owns are being infringed. Under penalty of perjury I certify that the information contained in the notification is both true and accurate, and I have the authority to act on behalf of the owner of the copyright(s) involved.

Should you have any queries, please let us know.

Thank you.

**Comment by ohthehugemanatee** [comment]
[copy/paste from email]

Hello Lawrence,

Thanks for reaching out. Can you explain what in the linked commit belongs to Deutsche Bank, or would require their authorization?

This is my own implementation of a client for the Deutsche Bank API. I used only publicly available information from the Deutsche Bank API documentation to build it. The linked commit in particular is a set of tests for my implementation. It doesn't even interact with the live API, only simulates it.

To my knowledge there is nothing in the repository that requires specific authorization from Deutsche Bank. I'll await further clarification or withdrawal of your request before taking further action.

Thanks

Campbell

**Comment by ohthehugemanatee** [comment]
Closing due to lack of response.
